name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Write public key
      run: 'mkdir -p keys && echo $PUBLIC_CERT > keys/public.key'
      shell: bash
      env:
        PUBLIC_CERT: ${{secrets.PUBLIC_CERT}}
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build for Linux x64
      run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -o publish/linux
      
    - name: Build for Windows x64
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o publish/windows
  
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.sha }}
        token: ${{ secrets.TOKEN }}
        files: |
           ${GITHUB_WORKSPACE}/publish/linux
           ${GITHUB_WORKSPACE}/publish/windows
